// Assembles the semantic-ui icon sprite from a curated token map.
//
//   node scripts/build-icons.mjs   (or: npm run build:icons)
//
// Reads icons/icons.json (semantic-token -> lucide-id + raw passthrough ids),
// pulls each icon's SVG from the lucide-static package, and writes a single
// <svg><symbol id="token">…</symbol></svg> sprite to
//   src/main/resources/icons.svg
// which the Maven resources-plugin copies to /sui/icons.svg.
//
// The sprite is a COMMITTED, generated artifact: the Maven build only copies
// it (no Node needed at build time). Re-run this script — and commit the
// result — whenever icons/icons.json changes. lucide-static is a devDependency
// used only here, never shipped.
//
// Swapping the icon library: install that library's static-SVG package,
// change LIB_ICON_DIR + the ids in icons.json, and regenerate. The semantic
// tokens (and therefore all app JSON) stay identical.

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const LIB_ICON_DIR = join(ROOT, "node_modules", "lucide-static", "icons");
const SPEC_PATH = join(ROOT, "icons", "icons.json");
const OUT_PATH = join(ROOT, "src", "main", "resources", "icons.svg");

// Stroke attributes live on each <symbol> so paths inherit them; the host
// <svg class="sui-icon"><use/></svg> only controls size (1em) and color
// (currentColor). Mirrors Lucide's own root-svg attributes.
const SYMBOL_ATTRS =
  'viewBox="0 0 24 24" fill="none" stroke="currentColor" ' +
  'stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';

/** Extracts the inner markup (paths, circles, …) of a Lucide SVG file. */
function innerSvg(lucideId) {
  const path = join(LIB_ICON_DIR, `${lucideId}.svg`);
  if (!existsSync(path)) {
    throw new Error(`lucide icon not found: ${lucideId} (${path})`);
  }
  const raw = readFileSync(path, "utf8");
  const open = raw.indexOf(">", raw.indexOf("<svg"));
  const close = raw.lastIndexOf("</svg>");
  return raw.slice(open + 1, close).replace(/\s*\n\s*/g, "").trim();
}

const spec = JSON.parse(readFileSync(SPEC_PATH, "utf8"));

// token -> lucideId. Aliases first; passthrough adds raw ids under their own
// name (skipping any already provided by an alias so ids stay unique).
const tokens = new Map();
for (const [token, lucideId] of Object.entries(spec.aliases ?? {})) {
  tokens.set(token, lucideId);
}
for (const lucideId of spec.passthrough ?? []) {
  if (!tokens.has(lucideId)) tokens.set(lucideId, lucideId);
}

const symbols = [];
for (const [token, lucideId] of [...tokens].sort((a, b) => a[0].localeCompare(b[0]))) {
  symbols.push(`<symbol id="${token}" ${SYMBOL_ATTRS}>${innerSvg(lucideId)}</symbol>`);
}

const sprite =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<!-- Generated by scripts/build-icons.mjs from icons/icons.json. Do not edit by hand. -->\n` +
  `<!-- Icons: Lucide (https://lucide.dev), ISC License. -->\n` +
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n` +
  symbols.map(s => "  " + s).join("\n") +
  `\n</svg>\n`;

writeFileSync(OUT_PATH, sprite, "utf8");
console.log(`✔ wrote ${OUT_PATH} — ${symbols.length} icons`);
